### ISSUE TITLE
v0.6.0 release updates

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb.github.io#178]
https://github.com/GlareDB/glaredb/releases/tag/v0.6.0

## Tasks

- [x] #185
  - [x] Add page(s) to Cloud grouping
  - [x] Document how billing works
  - [x] Document how to upgrade plan
  - [x] Document how to cancel plan
  - [x] Update: https://docs.glaredb.com/docs/about/free-tier.html
  - [x] Add GlareDB Pro information to: https://docs.glaredb.com/
- [x] #184
- [ ] #186
- [ ] #187
- [ ] #188
- [ ] #189
  - [ ] PostgreSQL
  - [ ] MySQL
