### ISSUE TITLE
[Epic] New Navigation

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb.github.io#224]
- [ ] Rearchitect documentation
- [ ] Fix or redirect stale links in documentation, site and product
- [ ] Close stale issues
- [ ] Create any new issues with follow-up items

**Comment by greyscaled** [comment]
I have started this work here: https://github.com/GlareDB/glaredb.github.io/tree/rearch
