### ISSUE TITLE
Chore: Rework early access

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb.github.io#65]
## Description

Early access is being converted to open access. This change comes after website changes.

### Tasks

- [x] Update early access button/links
- [x] Update Getting started https://docs.glaredb.com/docs/about/getting-started.html
- [x] Add language about free, links to product

**Comment by greyscaled** [comment]
Note: not yet merged (delayed merge to keep docs from getting out of date)

But was approved in #68
